/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface Document {
  'tipe' : DocumentType,
  'fileName' : string,
  'fileReference' : FileReference,
}
export type DocumentType = { 'KK' : null } |
  { 'Akta' : null } |
  { 'Ijazah' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type FileReference = Uint8Array;
export interface MedicalRecord {
  'golonganDarah' : string,
  'riwayatCedera' : string,
  'alergi' : string,
  'kondisiKhusus' : string,
}
export interface Player {
  'id' : bigint,
  'namaLengkap' : string,
  'tanggalLahir' : string,
  'nomorPunggung' : bigint,
  'riwayatMedis' : MedicalRecord,
  'alamat' : string,
  'foto' : FileReference,
  'nisn' : string,
  'dokumen' : Array<Document>,
  'statistik' : PlayerStats,
  'timestamp' : Timestamp,
  'kontak' : string,
  'posisi' : Position,
}
export interface PlayerInput {
  'namaLengkap' : string,
  'tanggalLahir' : string,
  'nomorPunggung' : bigint,
  'riwayatMedis' : MedicalRecord,
  'alamat' : string,
  'foto' : FileReference,
  'nisn' : string,
  'dokumen' : Array<Document>,
  'statistik' : PlayerStats,
  'kontak' : string,
  'posisi' : Position,
}
export interface PlayerStats {
  'gol' : bigint,
  'pertandingan' : bigint,
  'assist' : bigint,
}
export interface PlayerStatsSummary {
  'distribusi' : PositionDistribution,
  'totalPemain' : bigint,
}
export interface PlayerUpdate {
  'namaLengkap' : [] | [string],
  'tanggalLahir' : [] | [string],
  'nomorPunggung' : [] | [bigint],
  'riwayatMedis' : [] | [MedicalRecord],
  'alamat' : [] | [string],
  'foto' : [] | [FileReference],
  'nisn' : [] | [string],
  'dokumen' : [] | [Array<Document>],
  'statistik' : [] | [PlayerStats],
  'kontak' : [] | [string],
  'posisi' : [] | [Position],
}
export type Position = { 'DF' : null } |
  { 'FW' : null } |
  { 'GK' : null } |
  { 'MF' : null };
export interface PositionDistribution {
  'df' : bigint,
  'fw' : bigint,
  'gk' : bigint,
  'mf' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__nextId' : ActorMethod<[], any>,
  '__players' : ActorMethod<[], any>,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addPlayer' : ActorMethod<[PlayerInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePlayer' : ActorMethod<[bigint], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'filterPlayers' : ActorMethod<[Position], Array<Player>>,
  'generatePlayerPDF' : ActorMethod<[bigint], Uint8Array>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlayer' : ActorMethod<[bigint], [] | [Player]>,
  'getPlayerStats' : ActorMethod<[], PlayerStatsSummary>,
  'getPlayers' : ActorMethod<[], Array<Player>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'schema' : ActorMethod<[], string>,
  'searchPlayers' : ActorMethod<[string], Array<Player>>,
  'updatePlayer' : ActorMethod<[bigint, PlayerUpdate], [] | [Player]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];