/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const MedicalRecord = IDL.Record({
  'golonganDarah' : IDL.Text,
  'riwayatCedera' : IDL.Text,
  'alergi' : IDL.Text,
  'kondisiKhusus' : IDL.Text,
});
export const FileReference = IDL.Vec(IDL.Nat8);
export const DocumentType = IDL.Variant({
  'KK' : IDL.Null,
  'Akta' : IDL.Null,
  'Ijazah' : IDL.Null,
});
export const Document = IDL.Record({
  'tipe' : DocumentType,
  'fileName' : IDL.Text,
  'fileReference' : FileReference,
});
export const PlayerStats = IDL.Record({
  'gol' : IDL.Nat,
  'pertandingan' : IDL.Nat,
  'assist' : IDL.Nat,
});
export const Position = IDL.Variant({
  'DF' : IDL.Null,
  'FW' : IDL.Null,
  'GK' : IDL.Null,
  'MF' : IDL.Null,
});
export const PlayerInput = IDL.Record({
  'namaLengkap' : IDL.Text,
  'tanggalLahir' : IDL.Text,
  'nomorPunggung' : IDL.Nat,
  'riwayatMedis' : MedicalRecord,
  'alamat' : IDL.Text,
  'foto' : FileReference,
  'nisn' : IDL.Text,
  'dokumen' : IDL.Vec(Document),
  'statistik' : PlayerStats,
  'kontak' : IDL.Text,
  'posisi' : Position,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Timestamp = IDL.Int;
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'namaLengkap' : IDL.Text,
  'tanggalLahir' : IDL.Text,
  'nomorPunggung' : IDL.Nat,
  'riwayatMedis' : MedicalRecord,
  'alamat' : IDL.Text,
  'foto' : FileReference,
  'nisn' : IDL.Text,
  'dokumen' : IDL.Vec(Document),
  'statistik' : PlayerStats,
  'timestamp' : Timestamp,
  'kontak' : IDL.Text,
  'posisi' : Position,
});
export const PositionDistribution = IDL.Record({
  'df' : IDL.Nat,
  'fw' : IDL.Nat,
  'gk' : IDL.Nat,
  'mf' : IDL.Nat,
});
export const PlayerStatsSummary = IDL.Record({
  'distribusi' : PositionDistribution,
  'totalPemain' : IDL.Nat,
});
export const PlayerUpdate = IDL.Record({
  'namaLengkap' : IDL.Opt(IDL.Text),
  'tanggalLahir' : IDL.Opt(IDL.Text),
  'nomorPunggung' : IDL.Opt(IDL.Nat),
  'riwayatMedis' : IDL.Opt(MedicalRecord),
  'alamat' : IDL.Opt(IDL.Text),
  'foto' : IDL.Opt(FileReference),
  'nisn' : IDL.Opt(IDL.Text),
  'dokumen' : IDL.Opt(IDL.Vec(Document)),
  'statistik' : IDL.Opt(PlayerStats),
  'kontak' : IDL.Opt(IDL.Text),
  'posisi' : IDL.Opt(Position),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__players' : IDL.Func([], [IDL.Reserved], ['query']),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addPlayer' : IDL.Func([PlayerInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePlayer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'filterPlayers' : IDL.Func([Position], [IDL.Vec(Player)], ['query']),
  'generatePlayerPDF' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat8)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
  'getPlayerStats' : IDL.Func([], [PlayerStatsSummary], ['query']),
  'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchPlayers' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
  'updatePlayer' : IDL.Func([IDL.Nat, PlayerUpdate], [IDL.Opt(Player)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const MedicalRecord = IDL.Record({
    'golonganDarah' : IDL.Text,
    'riwayatCedera' : IDL.Text,
    'alergi' : IDL.Text,
    'kondisiKhusus' : IDL.Text,
  });
  const FileReference = IDL.Vec(IDL.Nat8);
  const DocumentType = IDL.Variant({
    'KK' : IDL.Null,
    'Akta' : IDL.Null,
    'Ijazah' : IDL.Null,
  });
  const Document = IDL.Record({
    'tipe' : DocumentType,
    'fileName' : IDL.Text,
    'fileReference' : FileReference,
  });
  const PlayerStats = IDL.Record({
    'gol' : IDL.Nat,
    'pertandingan' : IDL.Nat,
    'assist' : IDL.Nat,
  });
  const Position = IDL.Variant({
    'DF' : IDL.Null,
    'FW' : IDL.Null,
    'GK' : IDL.Null,
    'MF' : IDL.Null,
  });
  const PlayerInput = IDL.Record({
    'namaLengkap' : IDL.Text,
    'tanggalLahir' : IDL.Text,
    'nomorPunggung' : IDL.Nat,
    'riwayatMedis' : MedicalRecord,
    'alamat' : IDL.Text,
    'foto' : FileReference,
    'nisn' : IDL.Text,
    'dokumen' : IDL.Vec(Document),
    'statistik' : PlayerStats,
    'kontak' : IDL.Text,
    'posisi' : Position,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Timestamp = IDL.Int;
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'namaLengkap' : IDL.Text,
    'tanggalLahir' : IDL.Text,
    'nomorPunggung' : IDL.Nat,
    'riwayatMedis' : MedicalRecord,
    'alamat' : IDL.Text,
    'foto' : FileReference,
    'nisn' : IDL.Text,
    'dokumen' : IDL.Vec(Document),
    'statistik' : PlayerStats,
    'timestamp' : Timestamp,
    'kontak' : IDL.Text,
    'posisi' : Position,
  });
  const PositionDistribution = IDL.Record({
    'df' : IDL.Nat,
    'fw' : IDL.Nat,
    'gk' : IDL.Nat,
    'mf' : IDL.Nat,
  });
  const PlayerStatsSummary = IDL.Record({
    'distribusi' : PositionDistribution,
    'totalPemain' : IDL.Nat,
  });
  const PlayerUpdate = IDL.Record({
    'namaLengkap' : IDL.Opt(IDL.Text),
    'tanggalLahir' : IDL.Opt(IDL.Text),
    'nomorPunggung' : IDL.Opt(IDL.Nat),
    'riwayatMedis' : IDL.Opt(MedicalRecord),
    'alamat' : IDL.Opt(IDL.Text),
    'foto' : IDL.Opt(FileReference),
    'nisn' : IDL.Opt(IDL.Text),
    'dokumen' : IDL.Opt(IDL.Vec(Document)),
    'statistik' : IDL.Opt(PlayerStats),
    'kontak' : IDL.Opt(IDL.Text),
    'posisi' : IDL.Opt(Position),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__players' : IDL.Func([], [IDL.Reserved], ['query']),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addPlayer' : IDL.Func([PlayerInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePlayer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'filterPlayers' : IDL.Func([Position], [IDL.Vec(Player)], ['query']),
    'generatePlayerPDF' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat8)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
    'getPlayerStats' : IDL.Func([], [PlayerStatsSummary], ['query']),
    'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchPlayers' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
    'updatePlayer' : IDL.Func([IDL.Nat, PlayerUpdate], [IDL.Opt(Player)], []),
  });
};

export const init = ({ IDL }) => { return []; };